name: Publish NPM Packages

on:
  release:
    types: published

  workflow_dispatch:
    inputs:
      ref:
        description: 'commit/tag/branch to release from'
        required: true

jobs:
  setup:
    uses: looker-open-source/reusable-actions/.github/workflows/primary-version.yml@main

  publish:
    needs: setup
    if: >
      (github.event.inputs) ||
      (startsWith(github.event.release.tag_name, 'sdk-codegen-all') &&
      !github.event.release.draft &&
      !github.event.release.prerelease)
    runs-on: ubuntu-latest
      - name: Check that Looker is ready
        run: |
          ${{ github.workspace }}/.github/scripts/wait_for_looker.sh

      - name: Publish to NPM registry
        run: $(npm bin)/lerna publish from-package --yes --no-verify-access
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
