name: Publish NPM Packages

on:
  release:
    types: published

  workflow_dispatch:
    inputs:
      ref:
        description: 'commit/tag/branch to release from'
        required: true

jobs:
  setup:
    uses: looker-open-source/reusable-actions/.github/workflows/primary-version.yml@main

  publish:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - name: Publish to NPM registry
      run: npx lerna init && npx lerna publish from-package --yes --no-verify-access
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
