name: Publish NPM Packages

on:
  release:
    types: published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Publish to NPM registry
      run: npx lerna publish from-package --yes --no-verify-access
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
