name: Publish NPM Packages

on:
  release:
    types: published

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'
      - name: Build Packages
        if: ${{ github.event.release.outputs.releases_created }}
        run: |
          npm install
          npx lerna bootstrap

      - name: Publish to NPM
        if: ${{ github.event.release.outputs.releases_created }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: npx lerna publish from-package --yes --no-verify-access
