name: Publish NPM Packages

on:
  release:
    types: published

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test ${{ github.event.release.name }} Description ${{ github.event.release.body }} Output {{github.event.release.outputs}} Output {{github.event.release.output}}"
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org'
      - name: Build Packages
        run: npx lerna bootstrap

      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: npx lerna publish from-package --yes --no-verify-access
