name: Release

on:
  workflow_dispatch:
    inputs:
      type:
        description: 'Release Type'
        required: true
        default: 'dry-run'
        type: choice
        options:
          - dry-run
          - release
          - release-beta
          - release-next

env:
  node-version: 18.x

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Use Node v${{ env.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: ${{ env.node-version }}

      - name: Install NPM Dependencies
        run: npm ci

      - name: Run Semantic Release
        if: ${{ inputs.type == 'release' }}
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: npx release-it
