name: release-please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          default-branch: main
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          versioning-strategy: default
          release-type: node
          command: manifest
          monorepo-tags: true
          changelog-types: '[
            {"type":"feat","section":"Features","hidden":false},
            {"type":"chore","section":"Miscellaneous","hidden":false},
            {"type":"fix", "section":"*MINOR VERSION*","hidden":false},
            {"type":"style", "section":"*MINOR VERSION*","hidden":false},
            {"type":"refactor", "section":"*MINOR VERSION*","hidden":false},
          ]'
          pull-request-title-pattern: 'chore${scope}: release${component} ${version}'
      - name: Checkout Repository
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        if: ${{ steps.release.outputs.releases_created }}
        with:
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org'
      - name: Publish to NPM
        if: ${{ steps.release.outputs.releases_created }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: npx lerna publish from-package --yes --no-verify-access