name: release-please-beta

on:
  push:
    branches:
      - main-beta

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          default-branch: main-beta
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          versioning-strategy: default
          release-type: node
          prerelease: pre-release
          command: manifest
          monorepo-tags: true
          changelog-types: '[
            {"type":"feat","section":"Features","hidden":false},
            {"type":"chore","section":"Miscellaneous","hidden":false},
            {"type":"fix", "section":"*MINOR VERSION*","hidden":false},
            {"type":"style", "section":"*MINOR VERSION*","hidden":false},
            {"type":"refactor", "section":"*MINOR VERSION*","hidden":false},
          ]'
          pull-request-title-pattern: 'chore${scope}: release${component} ${version}'
